### PR TITLE
feat: update the styling of developergigapayse

### PR DESCRIPTION
**Pull request by nh-g**
- [x] change logo
- [x] change app background color
- [x] change menu background 
- [x] change code area background
- [x] change meta title and description
- [x] add favicon

### CODE REVIEW

**Comment by navid-asgharzadeh** [comment]
I can not see the logo has been changed

Screenshot 2024-04-16 at 12 47 33

Also all the builds are failing

**Review by navid-asgharzadeh — COMMENTED** [review]
Nice!

Just had one question

**Comment by nh-g** [comment]
> I can not see the logo has been changed
> 
> Screenshot 2024-04-16 at 12 47 33
> Also all the builds are failing
Screenshot 2024-04-16 at 16 07 06
Are you sure it is succesfully deployed locally? This is what I see

**Comment by navid-asgharzadeh** [comment]
> > I can not see the logo has been changed
> > Screenshot 2024-04-16 at 12 47 33
> > Also all the builds are failing
> 
> Screenshot 2024-04-16 at 16 07 06 Are you sure it is succesfully deployed locally? This is what I see

Oh! I wasn't in your branch hahaha
All good 👍

**Review by navid-asgharzadeh — APPROVED** [review]

**Pull request merged**
